### ISSUE TITLE
Does not work anymore?

### ISSUE THREAD

**Issue by glepretre** [Ashish-Bansal/audio-only-youtube#105] opened 2023-06-09 14:48 UTC
Does not work on my machine anymore : I still have the message displayed when enabled but the video runs.

Is it a YouTube breaking change?

Google Chrome 114.0.5735.90 on Linux.

Can I bring you more info? Feel free to tell me.

**Comment by flmorse** [comment] 2023-06-10 18:20
Same

**Comment by Dr-Shadow** [comment] 2023-06-12 13:34
Same issue here

**Comment by kofta999** [comment] 2023-06-12 20:48
Same here

**Comment by guplem** [comment] 2023-06-13 08:11
Same in Chrome 114.0.5735.110 (Official Build) (64-bit).
OS: Windows 11 Pro 22621.1702

**Comment by shanmukhasix** [comment] 2023-06-17 06:06
Same. It seems other similar plugins are not working, so I think it's something YouTube did.

**Comment by EinUser2** [comment] 2023-06-17 09:56
Chrome 114.0.5735.134
Windows 10 Pro (22H2) 19045.3086
But I agree that Google probably has changed something on the YT Api that causes this.

I'm currently using this:
https://chrome.google.com/webstore/detail/audio-only-for-youtube/jbonboilhhoakibpodmnkkcfjhkbajmk

**Comment by glepretre** [comment] 2023-06-19 08:13
This extension still works but it only hides the video (still downloaded): https://chrome.google.com/webstore/detail/music-mode-for-youtube/abbpaepbpakcpipajigmlpnhlnbennna 
https://addons.mozilla.org/en-US/firefox/addon/music-mode-for-youtube/
And it's not open source :confused:

**Comment by p0lygun** [comment] 2023-06-19 19:02
hmmm ok so it look like extension is waiting for a url that has ['mime:audio'](https://github.com/Ashish-Bansal/audio-only-youtube/blob/master/src/js/background.ts#L67), but youtube seems to have shifted to `mime=video/webm`, although i think we can still only stream the audio using some way 🤔 , i'll dig around and make a PR

in the mean time you guys can use https://music.youtube.com/ ?

**Comment by Thunderarea** [comment] 2023-06-20 06:39
> This extension still works but it only hides the video (still downloaded): https://chrome.google.com/webstore/detail/music-mode-for-youtube/abbpaepbpakcpipajigmlpnhlnbennna https://addons.mozilla.org/en-US/firefox/addon/music-mode-for-youtube/ And it's not open source 😕

Hi, I am the developer of this extension. The extension used to block the video but after YouTube's latest changes, this feature stopped working. Now as you said, the extension only hides the video. 
YouTube still uses URLs with the mime=audio type. However, I have noticed that the response is of type application/vnd.yt-ump. I don't know if this was also the case before the latest YouTube changes. Another thing that I noticed, and this is why YouTube does not longer plays the  audio files, is that all the URLs, video or audio, are now not playable by their own. In the past, when you opened one of these URLs in a separate tab, it played the video or audio (depending on the type of the URL). However, now when you open one of these URLs in a separate tab, it downloads a file instead of playing it. So, that's why when you put one of these audio files in the YouTube player, it refuses to play it. I don't know why this happens. Probably, its the thing with the returned content type. But, I say again I don't know if this was also the returned type in the past. 
Regarding the code of the extension, I plan to make it open source after a refactoring that I want to do before make it public (better functions and variables names and things like that).
I think that we have to organize a community to try to fix this issue. 
![image](https://github.com/Ashish-Bansal/audio-only-youtube/assets/27777837/9178d28b-103b-4e7b-9a5e-45e891a7c9ff)

**Comment by xDroni** [comment] 2023-06-23 19:01
I've created a pull request with the fix:

https://github.com/Ashish-Bansal/audio-only-youtube/pull/108

**Comment by Ashish-Bansal** [comment] 2023-06-24 23:44
Thanks @xDroni for the fix! 

I have submitted a new build to Chrome Store, it's currently in a review state.

**Comment by Ashish-Bansal** [comment] 2023-06-24 23:47
@Thunderarea Yes, that's right. It's because of the content type change. 

Fortunately, for now, we are able to control the content type through query param `ump`, but it may not be true in the future and we may need to find some other way.

**Comment by glepretre** [comment] 2023-06-26 13:15
Tried the updated 0.10.0 version : works again :blush: :partying_face: Thanks @xDroni and everyone for contributing :pray:

**Comment by p0lygun** [comment] 2023-06-28 17:39
pin and close this ?

**Closed as completed** 2023-06-28 20:20 UTC

**Comment by ValkivirIceUse** [comment] 2024-08-27 07:27
2 months and still not working as before.

**Comment by Thunderarea** [comment] 2024-08-27 13:41
Unfortunately, YouTube has again changed the way that delivers the video in the desktop version. So, now, YouTube sends a file that contains both audio and video and not separate files for audio and video. Thus, you cannot block the video and play only the audio (at least in the way that we did it till now). In YouTube Music and YouTube for mobiles the video and audio are still delivered in separate files

**Comment by ValkivirIceUse** [comment] 2024-09-02 06:50
Doesn't work again? Or need to sth MENTIONED above? Heard that same complicated scripts (hell documentations on web page have so many pages that it caused lags), i will link supposedly working today of i won't forget, just search audio yt, and the biggest file with its
Duplicate of # branches (as those are other scripts, am i right?)

**Comment by 3052** [comment] 2024-09-29 18:13
> Fortunately, for now, we are able to control the content type through query param `ump`, but it may not be true in the future and we may need to find some other way.

is this still the case? I just tried it and still got UMP response
