### ISSUE TITLE
List of Compatible videos 

### ISSUE THREAD

**Issue by zekrom-vale** [Ashish-Bansal/audio-only-youtube#6] opened 2017-04-12 22:13 UTC
This is for debug purposes trying to find out the error.
I have noticed that there is a big decrease in network activity.

https://www.youtube.com/watch?v=Rt3Z2TKfWe0

**Comment by Ashish-Bansal** [comment] 2017-04-13 01:31
A lot of users have reported that this extension doesn't work on longer videos.

So, I just tried this video and found that before it starts playing audio it downloads whole audio and then plays it. That could be the issue. Although I didn't check it thoroughly.

**Comment by Ashish-Bansal** [comment] 2017-04-13 01:39
Another video example : https://www.youtube.com/watch?v=-J7Dg9M6HJo

In this case, it downloads 85MB audio file and then starts playing it.
This can be confirmed in the Network Tab of Chrome Developer Console. Filter urls with "videoplayback".

Video Source : Chrome Webstore

**Comment by craftwar** [comment] 2018-02-04 03:34
What kind of error? I try my extension to two above video, it plays immediately.

**Comment by Ashish-Bansal** [comment] 2018-02-09 22:37
Looks like this was a bug in the Youtube's player which used to download the whole audio stream before playing it. Now it seems to be fixed. Closing issue. Thanks! @craftwar

**Closed as completed by Ashish-Bansal** 2018-02-09 22:37 UTC
Labels: bug, help wanted
